using System;
using System.IO;
using ValveMultitool.Models.Formats.Lump;

namespace ValveMultitool.Models.Formats.GameStats.Legacy.Custom.Ep2
{
    /// <summary>
    /// Generic statistics records.
    /// These are used in Episode 2 to primarily store achievement information.
    /// They are also used to store inputs from the point_gamestats_counter entity,
    /// Generated by Increment (name) and SetName inputs.
    /// </summary>
    public class Ep2GenericStats : LumpElement
    {
        private const ushort LumpVersion = 1;
        private static readonly LumpElementHeaderInfo HeaderInfo = new LumpElementHeaderInfo
        {
            Type = LumpElementHeaderInfo.HeaderNameType.String
        };

        public override void Read(BinaryReader reader, byte version)
        {
            var ver = reader.ReadInt16();
            if (ver != LumpVersion)
                throw new InvalidOperationException("Unsupported lump version.");

            ReadChildren<Ep2GenericStatsRecord>(reader, version, HeaderInfo);
        }

        public override void Write(BinaryWriter writer, byte version)
        {
            writer.Write(LumpVersion);
            WriteChildren(writer, version, HeaderInfo);
        }
    }
}
